### ISSUE TITLE
protectedRoute middleware protects routes not currently being called

### ISSUE THREAD

**Issue by dbarkowsky** [bcgov/citz-imb-kc-express#14]
## Issue
The `protectedRoute` middleware appears to be blocking requests to routers even if the same protections are not applied to those routers. This only happens if the routers with stricter role protections come before other routers. 

For example:
``` ts
app.use(`/api`, protectedRoute(), router1);
app.use(`/api`, protectedRoute(['admin']), router2);
```
This is fine. 
If we are trying to hit `/api`, Route 1 sees that there is a key and the request is handled there. We never get to Route 2.
If we are trying to hit `/api`, Route 1 sees that there is a key and lets the request pass by, then Route 2 either sees the user has the `admin` role and handles the request or rejects it or lacking the role.

``` ts
app.use(`/api`, protectedRoute(['admin']), router2);
app.use(`/api`, protectedRoute(), router1);
```
This order doesn't work.
Requests to Route 2 work as expected, but the request to Route 1 seems to get screened based on the requirements of Route 2. If the user doesn't have the Admin role when accessing Route 1, the request appears to get rejected with the following message:
``` json
{
  "error": "User must have all of the following roles: [admin]"
}
```

## Expected
Assumed that each route would be validated on an individual basis only if that route was accessed. Routes not currently being accessed should not have their validation checked.

## Temporary(?) Workaround
If you specify unique route paths in `express.ts`, the non-called routes are never checked. 
``` ts
app.use(`/api/route2`, protectedRoute(['admin']), router2);
app.use(`/api/route1`, protectedRoute(), router1);
```
This works fine.

**Comment by BradyMitch** [comment]
This seems like a limitation of express. I wouldn't use the same route twice and would opt for the unique route approach. There is possibly other options for using the middleware within the router instead but I'll have to do some experimentation.

At the least I can try to update the readme to make this more clear.
