### ISSUE TITLE
Importing getUserInfo and calling the function raises an error

### ISSUE THREAD

**Issue by GrahamS-Quartech** [bcgov/citz-imb-kc-express#19]
Importing as such:  `import { getUserInfo } from '@bcgov/citz-imb-kc-express';`

And then calling as such:
```
const ExampleRouter = () => {
    const exampleRouter = express.Router();
  
    exampleRouter .get("/", (req, res) => {
        
        res.status(200).json(getUserInfo(req.token));
    });

    return exampleRouter ;
}
```

It raises `TypeError: (0 , citz_imb_kc_express_1.getUserInfo) is not a function`. Same with parseJWT.

Tested using node v18.16, typescript v5.3.

**Comment by BradyMitch** [comment]
@GrahamS-Quartech I didn't intend for anyone to use that function outside of the inner workings of the package. I will make an update to the README.

```bash
# Use the following variable within controllers to access the user data.
const user = req.user; # This will be of type KeycloakUser
```

Thanks for the collaboration and feedback.
