### ISSUE TITLE
Initialization has a console.log that appears when running

### ISSUE THREAD

**Issue by dbarkowsky** [bcgov/citz-imb-kc-express#6]
<img width="633" alt="image" src="https://github.com/bcgov/citz-imb-kc-express/assets/37922247/9cf36beb-5c72-4946-a28e-5d54886c8cda">

This console log appears when the express app is initialized. Would be nice to have this removed or suppressed unless DEBUG is true.

**Comment by BradyMitch** [comment]
@dbarkowsky You don't like seeing a start up message? Could definitely add it to debug

**Comment by BradyMitch** [comment]
Resolved in https://github.com/bcgov/citz-imb-kc-express/pull/8
